// Built in list of common foods and an approximate calorie count per
// listed serving. These are general reference values, not exact for
// every brand or preparation method.
const KNOWN_FOODS = [
  { name: "Apple, medium", calories: 95 },
  { name: "Banana, medium", calories: 105 },
  { name: "Orange, medium", calories: 62 },
  { name: "Avocado, half", calories: 120 },
  { name: "Grapes, 1 cup", calories: 62 },
  { name: "Strawberries, 1 cup", calories: 49 },
  { name: "Blueberries, 1 cup", calories: 84 },
  { name: "White rice, 1 cup cooked", calories: 205 },
  { name: "Brown rice, 1 cup cooked", calories: 216 },
  { name: "Oatmeal, 1 cup cooked", calories: 166 },
  { name: "Whole wheat bread, 1 slice", calories: 81 },
  { name: "White bread, 1 slice", calories: 75 },
  { name: "Bagel, plain", calories: 245 },
  { name: "Pasta, 1 cup cooked", calories: 221 },
  { name: "Potato, medium baked", calories: 161 },
  { name: "Sweet potato, medium baked", calories: 103 },
  { name: "Egg, large", calories: 72 },
  { name: "Egg white, large", calories: 17 },
  { name: "Chicken breast, 100g grilled", calories: 165 },
  { name: "Chicken thigh, 100g cooked", calories: 209 },
  { name: "Ground beef, 100g cooked, lean", calories: 217 },
  { name: "Salmon, 100g cooked", calories: 208 },
  { name: "Tuna, canned in water, 100g", calories: 116 },
  { name: "Shrimp, 100g cooked", calories: 99 },
  { name: "Turkey breast, 100g cooked", calories: 135 },
  { name: "Tofu, 100g", calories: 76 },
  { name: "Greek yogurt, plain, 170g", calories: 100 },
  { name: "Yogurt, whole milk, 170g", calories: 149 },
  { name: "Milk, whole, 1 cup", calories: 149 },
  { name: "Milk, skim, 1 cup", calories: 83 },
  { name: "Cheddar cheese, 1 slice", calories: 113 },
  { name: "Cottage cheese, 1 cup", calories: 206 },
  { name: "Almonds, 28g (about 23)", calories: 164 },
  { name: "Peanut butter, 2 tbsp", calories: 188 },
  { name: "Walnuts, 28g", calories: 185 },
  { name: "Olive oil, 1 tbsp", calories: 119 },
  { name: "Butter, 1 tbsp", calories: 102 },
  { name: "Avocado oil, 1 tbsp", calories: 124 },
  { name: "Broccoli, 1 cup cooked", calories: 55 },
  { name: "Spinach, 1 cup raw", calories: 7 },
  { name: "Carrots, 1 cup raw", calories: 52 },
  { name: "Mixed salad greens, 2 cups", calories: 18 },
  { name: "Black beans, 1 cup cooked", calories: 227 },
  { name: "Chickpeas, 1 cup cooked", calories: 269 },
  { name: "Lentils, 1 cup cooked", calories: 230 },
  { name: "Hummus, 2 tbsp", calories: 70 },
  { name: "Dark chocolate, 30g", calories: 170 },
  { name: "Protein shake, 1 scoop with water", calories: 120 },
  { name: "Black coffee, 1 cup", calories: 2 },
  { name: "Coffee with milk, 1 cup", calories: 30 },
  { name: "Green tea, 1 cup", calories: 2 },
  { name: "Soda, 1 can", calories: 140 },
  { name: "Orange juice, 1 cup", calories: 112 },
  { name: "Pizza, 1 slice cheese", calories: 285 },
  { name: "Burger, fast food single patty", calories: 540 },
  { name: "French fries, medium", calories: 365 },
  { name: "Fried chicken, 1 piece", calories: 320 },
  { name: "Ice cream, 1 cup", calories: 273 },
  { name: "Granola bar", calories: 140 },
  { name: "Protein bar", calories: 200 }
];
