// Built in list of common workouts and an approximate calorie burn for
// a roughly 30 minute session at moderate intensity. Actual burn varies
// a lot by body weight, effort, and duration, so treat these as a
// starting point, not a precise measurement.
const KNOWN_WORKOUTS = [
  { name: "Walking, brisk (30 min)", calories: 150 },
  { name: "Running, moderate pace (30 min)", calories: 300 },
  { name: "Running, fast pace (30 min)", calories: 380 },
  { name: "Jogging (30 min)", calories: 240 },
  { name: "Cycling, moderate (30 min)", calories: 260 },
  { name: "Cycling, vigorous (30 min)", calories: 350 },
  { name: "Spin class (30 min)", calories: 300 },
  { name: "Swimming, laps (30 min)", calories: 300 },
  { name: "Water aerobics (30 min)", calories: 200 },
  { name: "Rowing machine (30 min)", calories: 260 },
  { name: "Elliptical (30 min)", calories: 270 },
  { name: "Stair climbing (30 min)", calories: 280 },
  { name: "Jump rope (30 min)", calories: 380 },
  { name: "Weight training (30 min)", calories: 180 },
  { name: "Bodyweight circuit (30 min)", calories: 220 },
  { name: "CrossFit style WOD (30 min)", calories: 400 },
  { name: "HIIT session (30 min)", calories: 350 },
  { name: "Kickboxing (30 min)", calories: 350 },
  { name: "Boxing training (30 min)", calories: 350 },
  { name: "Martial arts (30 min)", calories: 300 },
  { name: "Yoga (30 min)", calories: 120 },
  { name: "Pilates (30 min)", calories: 150 },
  { name: "Stretching and mobility (30 min)", calories: 80 },
  { name: "Dancing (30 min)", calories: 200 },
  { name: "Zumba (30 min)", calories: 260 },
  { name: "Hiking (30 min)", calories: 220 },
  { name: "Basketball (30 min)", calories: 300 },
  { name: "Soccer (30 min)", calories: 300 },
  { name: "Tennis (30 min)", calories: 260 },
  { name: "Golf, walking the course (30 min)", calories: 150 },
  { name: "Rock climbing (30 min)", calories: 300 },
  { name: "Skateboarding (30 min)", calories: 180 },
  { name: "Gardening, active (30 min)", calories: 150 },
  { name: "House cleaning, active (30 min)", calories: 120 }
];
